# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_DefiLlamaBase__initialize <- function(base_url, async, max_tries) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  return(invisible(NULL))
}

assert_return_DefiLlamaBase__initialize <- function(value) {
  assert_class(value, "DefiLlamaBase")
  return(value)
}

assert_args_DefiLlamaFees__initialize <- function(base_url, async, max_tries) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  return(invisible(NULL))
}

assert_return_DefiLlamaFees__initialize <- function(value) {
  assert_class(value, "DefiLlamaFees")
  return(value)
}

assert_args_DefiLlamaFees__get_fees_overview <- function(chain, data_type) {
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  assert_scalar_character(data_type)
  return(invisible(NULL))
}

assert_return_DefiLlamaFees__get_fees_overview <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "id", "name", "display_name", "module", "category", "protocol_type", "slug", "defillama_id", "logo", "chains", "parent_protocol", "total24h", "total7d", "total30d", "total1y", "total_all_time", "change_1d", "change_7d", "change_1m"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["display_name"]])
  assert_no_missing_values(value[["display_name"]])
  assert_character(value[["module"]])
  assert_no_missing_values(value[["module"]])
  assert_character(value[["category"]])
  assert_no_missing_values(value[["category"]])
  assert_character(value[["protocol_type"]])
  assert_no_missing_values(value[["protocol_type"]])
  assert_character(value[["slug"]])
  assert_no_missing_values(value[["slug"]])
  assert_character(value[["defillama_id"]])
  assert_no_missing_values(value[["defillama_id"]])
  assert_character(value[["logo"]])
  assert_no_missing_values(value[["logo"]])
  assert_character(value[["chains"]])
  assert_character(value[["parent_protocol"]])
  assert_double(value[["total24h"]])
  assert_double(value[["total7d"]])
  assert_double(value[["total30d"]])
  assert_double(value[["total1y"]])
  assert_double(value[["total_all_time"]])
  assert_double(value[["change_1d"]])
  assert_double(value[["change_7d"]])
  assert_double(value[["change_1m"]])
  return(value)
}

assert_args_DefiLlamaFees__get_fees_chart <- function(chain, data_type) {
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  assert_scalar_character(data_type)
  return(invisible(NULL))
}

assert_return_DefiLlamaFees__get_fees_chart <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "datetime", "value"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["value"]])
  return(value)
}

assert_args_DefiLlamaProtocols__initialize <- function(base_url, async, max_tries) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  return(invisible(NULL))
}

assert_return_DefiLlamaProtocols__initialize <- function(value) {
  assert_class(value, "DefiLlamaProtocols")
  return(value)
}

assert_return_DefiLlamaProtocols__get_protocols <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "name", "symbol", "chain", "category", "chains", "url", "logo", "gecko_id", "cmc_id", "parent_protocol", "tvl", "change_1h", "change_1d", "change_7d", "mcap", "staking", "pool2"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["chain"]])
  assert_character(value[["category"]])
  assert_no_missing_values(value[["category"]])
  assert_character(value[["chains"]])
  assert_character(value[["url"]])
  assert_no_missing_values(value[["url"]])
  assert_character(value[["logo"]])
  assert_no_missing_values(value[["logo"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["cmc_id"]])
  assert_character(value[["parent_protocol"]])
  assert_double(value[["tvl"]])
  assert_double(value[["change_1h"]])
  assert_double(value[["change_1d"]])
  assert_double(value[["change_7d"]])
  assert_double(value[["mcap"]])
  assert_double(value[["staking"]])
  assert_double(value[["pool2"]])
  return(value)
}

assert_args_DefiLlamaProtocols__get_protocol <- function(slug) {
  assert_scalar_character(slug)
  return(invisible(NULL))
}

assert_return_DefiLlamaProtocols__get_protocol <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("slug", "datetime", "tvl_usd"))
  assert_character(value[["slug"]])
  assert_no_missing_values(value[["slug"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["tvl_usd"]])
  return(value)
}

assert_return_DefiLlamaProtocols__get_chains <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "chain_id", "token_symbol", "gecko_id", "cmc_id", "tvl"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["chain_id"]])
  assert_character(value[["token_symbol"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["cmc_id"]])
  assert_double(value[["tvl"]])
  return(value)
}

assert_args_DefiLlamaProtocols__get_historical_chain_tvl <- function(chain) {
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_DefiLlamaProtocols__get_historical_chain_tvl <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("chain", "datetime", "tvl"))
  assert_character(value[["chain"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["tvl"]])
  return(value)
}

assert_args_DefiLlamaStablecoins__initialize <- function(base_url, async, max_tries) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  return(invisible(NULL))
}

assert_return_DefiLlamaStablecoins__initialize <- function(value) {
  assert_class(value, "DefiLlamaStablecoins")
  return(value)
}

assert_args_DefiLlamaStablecoins__get_stablecoins <- function(include_prices) {
  assert_scalar_logical(include_prices)
  return(invisible(NULL))
}

assert_return_DefiLlamaStablecoins__get_stablecoins <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "name", "symbol", "gecko_id", "peg_type", "peg_mechanism", "price", "price_source", "circulating", "circulating_prev_day", "circulating_prev_week", "circulating_prev_month", "chains"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["peg_type"]])
  assert_no_missing_values(value[["peg_type"]])
  assert_character(value[["peg_mechanism"]])
  assert_no_missing_values(value[["peg_mechanism"]])
  assert_double(value[["price"]])
  assert_character(value[["price_source"]])
  assert_double(value[["circulating"]])
  assert_double(value[["circulating_prev_day"]])
  assert_double(value[["circulating_prev_week"]])
  assert_double(value[["circulating_prev_month"]])
  assert_character(value[["chains"]])
  return(value)
}

assert_args_DefiLlamaStablecoins__get_stablecoin_charts <- function(stablecoin_id, chain) {
  if (!is.null(stablecoin_id)) {
    assert_any_of(
      stablecoin_id,
      function(.x) {
        assert_scalar_character(.x)
      },
      function(.x) {
        assert_scalar_count(.x)
        assert_between(.x, lower = 1)
      }
    )
  }
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_DefiLlamaStablecoins__get_stablecoin_charts <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("stablecoin_id", "datetime", "peg_type", "total_circulating", "total_circulating_usd", "total_unreleased", "total_minted_usd", "total_bridged_to_usd"))
  assert_character(value[["stablecoin_id"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["peg_type"]])
  assert_double(value[["total_circulating"]])
  assert_double(value[["total_circulating_usd"]])
  assert_double(value[["total_unreleased"]])
  assert_double(value[["total_minted_usd"]])
  assert_double(value[["total_bridged_to_usd"]])
  return(value)
}

assert_return_DefiLlamaStablecoins__get_stablecoin_chains <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "peg_type", "total_circulating_usd"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["peg_type"]])
  assert_double(value[["total_circulating_usd"]])
  return(value)
}

assert_args_DefiLlamaVolumes__initialize <- function(base_url, async, max_tries) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  return(invisible(NULL))
}

assert_return_DefiLlamaVolumes__initialize <- function(value) {
  assert_class(value, "DefiLlamaVolumes")
  return(value)
}

assert_args_DefiLlamaVolumes__get_dexs_overview <- function(chain, data_type) {
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  assert_scalar_character(data_type)
  return(invisible(NULL))
}

assert_return_DefiLlamaVolumes__get_dexs_overview <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "id", "name", "display_name", "module", "category", "protocol_type", "slug", "defillama_id", "logo", "chains", "parent_protocol", "total24h", "total7d", "total30d", "total1y", "total_all_time", "change_1d", "change_7d", "change_1m"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["display_name"]])
  assert_no_missing_values(value[["display_name"]])
  assert_character(value[["module"]])
  assert_no_missing_values(value[["module"]])
  assert_character(value[["category"]])
  assert_no_missing_values(value[["category"]])
  assert_character(value[["protocol_type"]])
  assert_no_missing_values(value[["protocol_type"]])
  assert_character(value[["slug"]])
  assert_no_missing_values(value[["slug"]])
  assert_character(value[["defillama_id"]])
  assert_no_missing_values(value[["defillama_id"]])
  assert_character(value[["logo"]])
  assert_no_missing_values(value[["logo"]])
  assert_character(value[["chains"]])
  assert_character(value[["parent_protocol"]])
  assert_double(value[["total24h"]])
  assert_double(value[["total7d"]])
  assert_double(value[["total30d"]])
  assert_double(value[["total1y"]])
  assert_double(value[["total_all_time"]])
  assert_double(value[["change_1d"]])
  assert_double(value[["change_7d"]])
  assert_double(value[["change_1m"]])
  return(value)
}

assert_args_DefiLlamaVolumes__get_dexs_chart <- function(chain, data_type) {
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  assert_scalar_character(data_type)
  return(invisible(NULL))
}

assert_return_DefiLlamaVolumes__get_dexs_chart <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "datetime", "value"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["value"]])
  return(value)
}

assert_args_defillama_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_defillama_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_defillama_stablecoins_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_defillama_stablecoins_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_empty_dt_pegged_assets <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "name", "symbol", "gecko_id", "peg_type", "peg_mechanism", "price", "price_source", "circulating", "circulating_prev_day", "circulating_prev_week", "circulating_prev_month", "chains"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["peg_type"]])
  assert_no_missing_values(value[["peg_type"]])
  assert_character(value[["peg_mechanism"]])
  assert_no_missing_values(value[["peg_mechanism"]])
  assert_double(value[["price"]])
  assert_character(value[["price_source"]])
  assert_double(value[["circulating"]])
  assert_double(value[["circulating_prev_day"]])
  assert_double(value[["circulating_prev_week"]])
  assert_double(value[["circulating_prev_month"]])
  assert_character(value[["chains"]])
  return(value)
}

assert_return_empty_dt_stablecoin_charts <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("stablecoin_id", "datetime", "peg_type", "total_circulating", "total_circulating_usd", "total_unreleased", "total_minted_usd", "total_bridged_to_usd"))
  assert_character(value[["stablecoin_id"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["peg_type"]])
  assert_double(value[["total_circulating"]])
  assert_double(value[["total_circulating_usd"]])
  assert_double(value[["total_unreleased"]])
  assert_double(value[["total_minted_usd"]])
  assert_double(value[["total_bridged_to_usd"]])
  return(value)
}

assert_return_empty_dt_stablecoin_chains <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "peg_type", "total_circulating_usd"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["peg_type"]])
  assert_double(value[["total_circulating_usd"]])
  return(value)
}

assert_return_empty_dt_protocols <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "name", "symbol", "chain", "category", "chains", "url", "logo", "gecko_id", "cmc_id", "parent_protocol", "tvl", "change_1h", "change_1d", "change_7d", "mcap", "staking", "pool2"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["chain"]])
  assert_character(value[["category"]])
  assert_no_missing_values(value[["category"]])
  assert_character(value[["chains"]])
  assert_character(value[["url"]])
  assert_no_missing_values(value[["url"]])
  assert_character(value[["logo"]])
  assert_no_missing_values(value[["logo"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["cmc_id"]])
  assert_character(value[["parent_protocol"]])
  assert_double(value[["tvl"]])
  assert_double(value[["change_1h"]])
  assert_double(value[["change_1d"]])
  assert_double(value[["change_7d"]])
  assert_double(value[["mcap"]])
  assert_double(value[["staking"]])
  assert_double(value[["pool2"]])
  return(value)
}

assert_return_empty_dt_protocol_tvl <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("slug", "datetime", "tvl_usd"))
  assert_character(value[["slug"]])
  assert_no_missing_values(value[["slug"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["tvl_usd"]])
  return(value)
}

assert_return_empty_dt_chain_tvl <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "chain_id", "token_symbol", "gecko_id", "cmc_id", "tvl"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["chain_id"]])
  assert_character(value[["token_symbol"]])
  assert_character(value[["gecko_id"]])
  assert_character(value[["cmc_id"]])
  assert_double(value[["tvl"]])
  return(value)
}

assert_return_empty_dt_chain_tvl_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("chain", "datetime", "tvl"))
  assert_character(value[["chain"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["tvl"]])
  return(value)
}

assert_return_empty_dt_dimension_overview <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "id", "name", "display_name", "module", "category", "protocol_type", "slug", "defillama_id", "logo", "chains", "parent_protocol", "total24h", "total7d", "total30d", "total1y", "total_all_time", "change_1d", "change_7d", "change_1m"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["display_name"]])
  assert_no_missing_values(value[["display_name"]])
  assert_character(value[["module"]])
  assert_no_missing_values(value[["module"]])
  assert_character(value[["category"]])
  assert_no_missing_values(value[["category"]])
  assert_character(value[["protocol_type"]])
  assert_no_missing_values(value[["protocol_type"]])
  assert_character(value[["slug"]])
  assert_no_missing_values(value[["slug"]])
  assert_character(value[["defillama_id"]])
  assert_no_missing_values(value[["defillama_id"]])
  assert_character(value[["logo"]])
  assert_no_missing_values(value[["logo"]])
  assert_character(value[["chains"]])
  assert_character(value[["parent_protocol"]])
  assert_double(value[["total24h"]])
  assert_double(value[["total7d"]])
  assert_double(value[["total30d"]])
  assert_double(value[["total1y"]])
  assert_double(value[["total_all_time"]])
  assert_double(value[["change_1d"]])
  assert_double(value[["change_7d"]])
  assert_double(value[["change_1m"]])
  return(value)
}

assert_return_empty_dt_dimension_chart <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("data_type", "datetime", "value"))
  assert_character(value[["data_type"]])
  assert_no_missing_values(value[["data_type"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["value"]])
  return(value)
}

assert_args_parse_defillama_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_defillama_response <- function(value) {
  if (!is.null(value)) {
    assert_list(value)
  }
  return(value)
}

